version: '3'

services:

  wordpress:
    image: wordpress
    container_name: wp-test-wp
    ports:
      - 8080:80
    volumes:
      - ./wordpress/:/var/www/html/:rw
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mariadb
    container_name: wp-test-db
    ports:
      - 3306:3306
    volumes:
      - ./data/:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: example
